-- xycyl finance ODS DDL v1
-- Target: public schema in dts-stack warehouse PostgreSQL.
-- Source database: rs_cloud_flower.
-- Safe mode: create missing tables only; no drop/truncate/data migration.

CREATE TABLE IF NOT EXISTS public.ods_ptr_mysql_a_month_accounting (
  id bigint,
  company_name varchar(255),
  project_id bigint,
  project_name varchar(128),
  settlement_year integer,
  settlement_month integer,
  year_and_month varchar(8),
  status integer,
  start_time timestamp without time zone,
  end_time timestamp without time zone,
  total_day integer,
  project_manage_user_id bigint,
  project_manage_user_name varchar(64),
  supervise_user_id bigint,
  supervise_user_name varchar(64),
  biz_user_id bigint,
  biz_user_name varchar(64),
  discount_rate double precision,
  bit_number integer,
  rent_type integer,
  regular_rent numeric(15,4),
  receivable_total_amount numeric(15,4),
  net_receipt_total_amount numeric(15,4),
  folding_after_total_amount numeric(15,4),
  period_total_amount numeric(15,4),
  period_receivable_total_amount numeric(15,4),
  period_net_receivable_total_amount numeric(15,4),
  add_total_amount numeric(15,4),
  add_receivable_total_amount numeric(15,4),
  add_net_receipt_total_amount numeric(15,4),
  cut_total_amount numeric(15,4),
  cut_receivable_total_amount numeric(15,4),
  cut_net_receipt_total_amount numeric(15,4),
  adjust_total_amount numeric(15,4),
  adjust_receivable_total_amount numeric(15,4),
  adjust_net_receipt_total_amount numeric(15,4),
  sale_total_amount numeric(15,4),
  sale_receipt_total_amount numeric(15,4),
  sale_net_receipt_total_amount numeric(15,4),
  update_time timestamp without time zone,
  update_user_id bigint,
  update_user_name varchar(64),
  total_amount numeric(15,4),
  offset_biz_ids varchar(255),
  department_id bigint,
  department_name varchar(255),
  contract_id bigint,
  _dts_source_system varchar(200),
  _dts_source_table varchar(300),
  _dts_import_time timestamp without time zone,
  _dts_batch_id varchar(128),
  _dts_execution_id varchar(128),
  _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS public.ods_ptr_mysql_a_collection_record (
  id bigint,
  code varchar(20),
  income_type integer,
  project_id bigint,
  project_name varchar(255),
  status integer,
  with_invoice integer,
  payment_type integer,
  pay_mode varchar(255),
  colloection_name varchar(255),
  colloection_bank_account varchar(255),
  pay_time timestamp without time zone,
  pay_amoney numeric(15,2),
  create_by bigint,
  create_time timestamp without time zone,
  update_by bigint,
  update_time timestamp without time zone,
  remark varchar(255),
  tenant_id bigint,
  _dts_source_system varchar(200),
  _dts_source_table varchar(300),
  _dts_import_time timestamp without time zone,
  _dts_batch_id varchar(128),
  _dts_execution_id varchar(128),
  _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS public.ods_ptr_mysql_f_voucher (
  id bigint,
  code varchar(100),
  account_priod varchar(50),
  biz_id bigint,
  biz_code varchar(100),
  biz_type integer,
  description varchar(500),
  memo varchar(500),
  status integer,
  total_debit_amount numeric(19,4),
  total_credit_amount numeric(19,4),
  create_by bigint,
  create_time timestamp without time zone,
  update_by bigint,
  update_time timestamp without time zone,
  remark varchar(500),
  _dts_source_system varchar(200),
  _dts_source_table varchar(300),
  _dts_import_time timestamp without time zone,
  _dts_batch_id varchar(128),
  _dts_execution_id varchar(128),
  _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS public.ods_ptr_mysql_f_voucher_item (
  id bigint,
  voucher_id bigint,
  voucher_code varchar(100),
  account_priod varchar(50),
  subject_id bigint,
  subject_code varchar(100),
  description varchar(500),
  gl_account varchar(200),
  detail_account varchar(200),
  debit_amount numeric(18,2),
  credit_amount numeric(18,2),
  memo varchar(500),
  status integer,
  create_by bigint,
  create_time timestamp without time zone,
  update_by bigint,
  update_time timestamp without time zone,
  remark varchar(500),
  _dts_source_system varchar(200),
  _dts_source_table varchar(300),
  _dts_import_time timestamp without time zone,
  _dts_batch_id varchar(128),
  _dts_execution_id varchar(128),
  _dts_task_id varchar(64)
);

COMMENT ON TABLE public.ods_ptr_mysql_a_month_accounting IS 'ODS mirror of rs_cloud_flower.a_month_accounting for xycyl finance settlement dbt models.';
COMMENT ON TABLE public.ods_ptr_mysql_a_collection_record IS 'ODS mirror of rs_cloud_flower.a_collection_record for xycyl finance collection dbt models.';
COMMENT ON TABLE public.ods_ptr_mysql_f_voucher IS 'ODS mirror of rs_cloud_flower.f_voucher for xycyl finance voucher dbt models.';
COMMENT ON TABLE public.ods_ptr_mysql_f_voucher_item IS 'ODS mirror of rs_cloud_flower.f_voucher_item for xycyl finance voucher item dbt models.';
