-- Sprint-30 F2 ODS create tables
-- Generated from adminapi/docker/mysql/db source DDL on 2026-06-01.
-- ODS keeps business columns as varchar/text; dbt STG owns type casting.

CREATE TABLE IF NOT EXISTS ods_ptr_mysql_t_warehousing_info (
    id varchar(500),
    storehouse_info_id varchar(500),
    code varchar(500),
    title varchar(500),
    warehousing_user_id varchar(500),
    warehousing_user_name varchar(500),
    warehousing_time varchar(500),
    status varchar(500),
    warehousing_type varchar(500),
    biz_id varchar(500),
    create_by varchar(500),
    create_time varchar(500),
    update_by varchar(500),
    update_time varchar(500),
    remark text,
    del_flag varchar(500),
    tenant_id varchar(500),
    print_status varchar(500),
    print_time varchar(500),
    print_user_id varchar(500),
    print_user_name varchar(500),
    _dts_source_system varchar(64) DEFAULT rs_cloud_flower,
    _dts_source_table varchar(128),
    _dts_import_time timestamp DEFAULT now(),
    _dts_batch_id varchar(64),
    _dts_execution_id varchar(64),
    _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS ods_ptr_mysql_t_warehousing_item (
    id varchar(500),
    warehousing_info_id varchar(500),
    good_price_id varchar(500),
    good_name varchar(500),
    good_type varchar(500),
    good_norms varchar(500),
    good_specs varchar(500),
    good_unit varchar(500),
    good_number varchar(500),
    price varchar(500),
    biz_item_id varchar(500),
    _dts_source_system varchar(64) DEFAULT rs_cloud_flower,
    _dts_source_table varchar(128),
    _dts_import_time timestamp DEFAULT now(),
    _dts_batch_id varchar(64),
    _dts_execution_id varchar(64),
    _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS ods_ptr_mysql_t_ex_warehouse_info (
    id varchar(500),
    code varchar(500),
    title varchar(500),
    storehouse_info_id varchar(500),
    status varchar(500),
    distribution_time varchar(500),
    distribution_user_id varchar(500),
    distribution_user_name varchar(500),
    ex_warehouse_time varchar(500),
    ex_warehouse_user_id varchar(500),
    ex_warehouse_user_name varchar(500),
    take_goods_time varchar(500),
    take_goods_user_id varchar(500),
    take_goods_user_name varchar(500),
    receive_time varchar(500),
    receive_user_id varchar(500),
    receive_user_name varchar(500),
    create_by varchar(500),
    create_time varchar(500),
    update_by varchar(500),
    update_time varchar(500),
    remark text,
    del_flag varchar(500),
    tenant_id varchar(500),
    out_house_type varchar(500),
    biz_id varchar(500),
    print_status varchar(500),
    print_time varchar(500),
    print_user_id varchar(500),
    print_user_name varchar(500),
    _dts_source_system varchar(64) DEFAULT rs_cloud_flower,
    _dts_source_table varchar(128),
    _dts_import_time timestamp DEFAULT now(),
    _dts_batch_id varchar(64),
    _dts_execution_id varchar(64),
    _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS ods_ptr_mysql_t_ex_warehouse_item (
    id varchar(500),
    ex_warehouse_info_id varchar(500),
    business_id varchar(500),
    flower_plant_item_id varchar(500),
    good_price_id varchar(500),
    good_name varchar(500),
    good_type varchar(500),
    good_norms varchar(500),
    good_specs varchar(500),
    good_unit varchar(500),
    good_number varchar(500),
    price varchar(500),
    _dts_source_system varchar(64) DEFAULT rs_cloud_flower,
    _dts_source_table varchar(128),
    _dts_import_time timestamp DEFAULT now(),
    _dts_batch_id varchar(64),
    _dts_execution_id varchar(64),
    _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS ods_ptr_mysql_a_month_accounting (
    id varchar(500),
    company_name varchar(500),
    project_id varchar(500),
    project_name varchar(500),
    settlement_year varchar(500),
    settlement_month varchar(500),
    year_and_month varchar(500),
    status varchar(500),
    start_time varchar(500),
    end_time varchar(500),
    total_day varchar(500),
    project_manage_user_id varchar(500),
    project_manage_user_name varchar(500),
    supervise_user_id varchar(500),
    supervise_user_name varchar(500),
    biz_user_id varchar(500),
    biz_user_name varchar(500),
    discount_rate varchar(500),
    bit_number varchar(500),
    rent_type varchar(500),
    regular_rent varchar(500),
    receivable_total_amount varchar(500),
    net_receipt_total_amount varchar(500),
    folding_after_total_amount varchar(500),
    period_total_amount varchar(500),
    period_receivable_total_amount varchar(500),
    period_net_receivable_total_amount varchar(500),
    add_total_amount varchar(500),
    add_receivable_total_amount varchar(500),
    add_net_receipt_total_amount varchar(500),
    cut_total_amount varchar(500),
    cut_receivable_total_amount varchar(500),
    cut_net_receipt_total_amount varchar(500),
    adjust_total_amount varchar(500),
    adjust_receivable_total_amount varchar(500),
    adjust_net_receipt_total_amount varchar(500),
    sale_total_amount varchar(500),
    sale_receipt_total_amount varchar(500),
    sale_net_receipt_total_amount varchar(500),
    update_time varchar(500),
    update_user_id varchar(500),
    update_user_name varchar(500),
    total_amount varchar(500),
    offset_biz_ids varchar(500),
    _dts_source_system varchar(64) DEFAULT rs_cloud_flower,
    _dts_source_table varchar(128),
    _dts_import_time timestamp DEFAULT now(),
    _dts_batch_id varchar(64),
    _dts_execution_id varchar(64),
    _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS ods_ptr_mysql_a_green_accounting (
    id varchar(500),
    month_accounting_id varchar(500),
    parent_id varchar(500),
    floor_number_id varchar(500),
    floor_number_name varchar(500),
    floor_layer_id varchar(500),
    floor_layer_name varchar(500),
    position_id varchar(500),
    position_name varchar(500),
    position_full_name varchar(500),
    curing_user_id varchar(500),
    curing_user_name varchar(500),
    contract_dept_id varchar(500),
    contract_dept_name varchar(500),
    plant_type varchar(500),
    good_name varchar(500),
    good_price_id varchar(500),
    good_type varchar(500),
    good_norms varchar(500),
    good_specs varchar(500),
    good_unit varchar(500),
    good_name_alias varchar(500),
    good_norms_alias varchar(500),
    rent varchar(500),
    real_rent varchar(500),
    cost varchar(500),
    good_number varchar(500),
    total_number varchar(500),
    source_type varchar(500),
    change_start_time varchar(500),
    change_end_time varchar(500),
    change_number varchar(500),
    change_unit varchar(500),
    total_rent varchar(500),
    total_real_rent varchar(500),
    total_after_folding_rent varchar(500),
    update_time varchar(500),
    update_user_id varchar(500),
    update_user_name varchar(500),
    discount_rate varchar(500),
    biz_id varchar(500),
    biz_code varchar(500),
    remark text,
    _dts_source_system varchar(64) DEFAULT rs_cloud_flower,
    _dts_source_table varchar(128),
    _dts_import_time timestamp DEFAULT now(),
    _dts_batch_id varchar(64),
    _dts_execution_id varchar(64),
    _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS ods_ptr_mysql_a_flower_biz_accounting (
    id varchar(500),
    month_accounting_id varchar(500),
    biz_id varchar(500),
    biz_type varchar(500),
    code varchar(500),
    title varchar(500),
    parent_id varchar(500),
    floor_number_id varchar(500),
    floor_number_name varchar(500),
    floor_layer_id varchar(500),
    floor_layer_name varchar(500),
    position_id varchar(500),
    position_name varchar(500),
    position_full_name varchar(500),
    good_name varchar(500),
    good_price_id varchar(500),
    good_type varchar(500),
    good_norms varchar(500),
    good_specs varchar(500),
    good_unit varchar(500),
    rent varchar(500),
    cost varchar(500),
    good_number varchar(500),
    total_number varchar(500),
    start_time varchar(500),
    plant_type varchar(500),
    adjust_type varchar(500),
    day_rent varchar(500),
    day_number varchar(500),
    total_rent varchar(500),
    finish_time varchar(500),
    _dts_source_system varchar(64) DEFAULT rs_cloud_flower,
    _dts_source_table varchar(128),
    _dts_import_time timestamp DEFAULT now(),
    _dts_batch_id varchar(64),
    _dts_execution_id varchar(64),
    _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS ods_ptr_mysql_a_sale_account (
    id varchar(500),
    biz_id varchar(500),
    settlement_type varchar(500),
    status varchar(500),
    finish_time varchar(500),
    update_time varchar(500),
    receivable_amount varchar(500),
    biz_amount varchar(500),
    net_receipts_amount varchar(500),
    total_cost varchar(500),
    invoice_status varchar(500),
    invoice_no varchar(500),
    invoice_time varchar(500),
    _dts_source_system varchar(64) DEFAULT rs_cloud_flower,
    _dts_source_table varchar(128),
    _dts_import_time timestamp DEFAULT now(),
    _dts_batch_id varchar(64),
    _dts_execution_id varchar(64),
    _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS ods_ptr_mysql_a_sale_account_rent_item (
    id varchar(500),
    settlement_month varchar(500),
    sale_account_id varchar(500),
    parent_id varchar(500),
    status varchar(500),
    green_type varchar(500),
    position_id varchar(500),
    position_name varchar(500),
    position_full_name varchar(500),
    good_name varchar(500),
    good_price_id varchar(500),
    good_type varchar(500),
    good_norms varchar(500),
    good_specs varchar(500),
    good_unit varchar(500),
    good_number varchar(500),
    total_number varchar(500),
    rent varchar(500),
    _dts_source_system varchar(64) DEFAULT rs_cloud_flower,
    _dts_source_table varchar(128),
    _dts_import_time timestamp DEFAULT now(),
    _dts_batch_id varchar(64),
    _dts_execution_id varchar(64),
    _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS ods_ptr_mysql_a_invoice_info (
    id varchar(500),
    project_id varchar(500),
    project_name varchar(500),
    bill_type varchar(500),
    code varchar(500),
    title varchar(500),
    status varchar(500),
    apply_user_id varchar(500),
    apply_user_name varchar(500),
    apply_time varchar(500),
    content text,
    apply_invoice_amoney varchar(500),
    invoice_time varchar(500),
    invoice_amoney varchar(500),
    invoice_user_id varchar(500),
    invoice_user_name varchar(500),
    invoice_no varchar(500),
    invoice_file_ids text,
    invoice_type varchar(500),
    tax_rate varchar(500),
    cname varchar(500),
    cno varchar(500),
    caddress varchar(500),
    ccontact_number varchar(500),
    cbank_name varchar(500),
    cbank_account varchar(500),
    pay_total_amount varchar(500),
    process_id varchar(500),
    create_by varchar(500),
    create_time varchar(500),
    update_time varchar(500),
    update_by varchar(500),
    remark text,
    _dts_source_system varchar(64) DEFAULT rs_cloud_flower,
    _dts_source_table varchar(128),
    _dts_import_time timestamp DEFAULT now(),
    _dts_batch_id varchar(64),
    _dts_execution_id varchar(64),
    _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS ods_ptr_mysql_a_invoice_item (
    id varchar(500),
    invoice_info_id varchar(500),
    biz_id varchar(500),
    title varchar(500),
    total_amount varchar(500),
    _dts_source_system varchar(64) DEFAULT rs_cloud_flower,
    _dts_source_table varchar(128),
    _dts_import_time timestamp DEFAULT now(),
    _dts_batch_id varchar(64),
    _dts_execution_id varchar(64),
    _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS ods_ptr_mysql_a_invoice_record (
    id varchar(500),
    invoice_info_id varchar(500),
    invoice_no varchar(500),
    invoice_amount varchar(500),
    invoice_file_ids text,
    invoice_time varchar(500),
    invoice_user_id varchar(500),
    invoice_user_name varchar(500),
    create_time varchar(500),
    _dts_source_system varchar(64) DEFAULT rs_cloud_flower,
    _dts_source_table varchar(128),
    _dts_import_time timestamp DEFAULT now(),
    _dts_batch_id varchar(64),
    _dts_execution_id varchar(64),
    _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS ods_ptr_mysql_a_collection_record (
    id varchar(500),
    code varchar(500),
    income_type varchar(500),
    project_id varchar(500),
    project_name varchar(500),
    status varchar(500),
    with_invoice varchar(500),
    payment_type varchar(500),
    pay_mode varchar(500),
    colloection_name varchar(500),
    colloection_bank_account varchar(500),
    pay_time varchar(500),
    pay_amoney varchar(500),
    create_by varchar(500),
    create_time varchar(500),
    update_by varchar(500),
    update_time varchar(500),
    remark text,
    tenant_id varchar(500),
    _dts_source_system varchar(64) DEFAULT rs_cloud_flower,
    _dts_source_table varchar(128),
    _dts_import_time timestamp DEFAULT now(),
    _dts_batch_id varchar(64),
    _dts_execution_id varchar(64),
    _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS ods_ptr_mysql_a_collection_item (
    id varchar(500),
    collection_record_id varchar(500),
    biz_id varchar(500),
    biz_type varchar(500),
    total_amount varchar(500),
    _dts_source_system varchar(64) DEFAULT rs_cloud_flower,
    _dts_source_table varchar(128),
    _dts_import_time timestamp DEFAULT now(),
    _dts_batch_id varchar(64),
    _dts_execution_id varchar(64),
    _dts_task_id varchar(64)
);
