{{ config(tags=['contract']) }}

SELECT
  o.id::bigint AS source_row_id,
  'ods_ptr_mysql_p_contract'::text AS source_table,
  COALESCE({{ nullif_placeholder("o._dts_source_system") }}, 'ptr_mysql') AS source_system,
  o._dts_import_time AS imported_at,

  o.id::bigint AS contract_id,
  o.customer_id::bigint AS customer_id,
  {{ nullif_placeholder("o.code") }} AS contract_code,
  {{ nullif_placeholder("o.title") }} AS contract_title,
  o.signing_time::timestamp AS signing_time,
  o.status::integer AS status_raw,
  o.start_date::timestamp AS start_date,
  o.end_date::timestamp AS end_date,
  {{ nullif_placeholder("o.type") }} AS contract_type_raw,
  {{ nullif_placeholder("o.settlement_method") }} AS settlement_method_raw,
  o.discount::numeric(18,2) AS discount_amount,
  o.business_personnel_id::bigint AS business_personnel_id,
  {{ nullif_placeholder("o.business_personnel_name") }} AS business_personnel_name,
  {{ nullif_placeholder("o.settlement_period") }} AS settlement_period_raw,
  {{ nullif_placeholder("o.settlement_period_custom") }} AS settlement_period_custom,
  o.invoice_type::integer AS invoice_type_raw,
  o.amount_excluding_tax::numeric(18,4) AS amount_excluding_tax,
  o.amount_including_tax::numeric(18,4) AS amount_including_tax,
  o.amount_including_tax_and::numeric(18,4) AS amount_including_tax_and,
  {{ nullif_placeholder("o.full_billing_name") }} AS full_billing_name,
  {{ nullif_placeholder("o.company_name") }} AS company_name,
  {{ nullif_placeholder("o.address") }} AS billing_address,
  {{ nullif_placeholder("o.duty_paragraph") }} AS duty_paragraph,
  {{ nullif_placeholder("o.bank") }} AS bank_name,
  {{ nullif_placeholder("o.bank_card_no") }} AS bank_card_no,
  {{ nullif_placeholder("o.contact_number") }} AS contact_number,
  o.invoicing_tax_rate::integer AS invoicing_tax_rate,
  o.parent_id::bigint AS parent_contract_id,
  o.active_child::bigint AS active_child_contract_id,
  o.tenant_id::bigint AS tenant_id,
  {{ nullif_placeholder("o.settlement_start_date") }} AS settlement_start_date_raw,
  o.verify_type::integer AS verify_type_raw,
  o.verify_day_number::integer AS verify_day_number,
  o.settlement_type::integer AS settlement_type_raw,
  o.month_settlement_money::numeric(18,4) AS month_settlement_money,
  o.discount_ratio::double precision AS discount_ratio,
  o.create_by::bigint AS created_by,
  o.create_time::timestamp AS created_at,
  o.update_by::bigint AS updated_by,
  o.update_time::timestamp AS updated_at,
  {{ nullif_placeholder("o.remark") }} AS remark
FROM {{ source('xycyl_project_ods', 'p_contract') }} o
WHERE COALESCE({{ nullif_placeholder("o.del_flag") }}, '0') = '0'
