{{ config(tags=['project']) }}

SELECT
  o.id::bigint AS source_row_id,
  'ods_ptr_mysql_p_project'::text AS source_table,
  COALESCE({{ nullif_placeholder("o._dts_source_system") }}, 'ptr_mysql') AS source_system,
  o._dts_import_time AS imported_at,

  o.id::bigint AS project_id,
  o.contract_id::bigint AS contract_id,
  {{ nullif_placeholder("o.name") }} AS project_name,
  {{ nullif_placeholder("o.code") }} AS project_code,
  {{ nullif_placeholder("o.abbreviation") }} AS project_abbreviation,
  o.status::integer AS status_raw,
  {{ nullif_placeholder("o.area") }} AS area_raw,
  o.type::integer AS project_type_raw,
  {{ nullif_placeholder("o.address") }} AS project_address,
  o.longitude::numeric(10,6) AS longitude,
  o.dimension::numeric(10,6) AS latitude,
  {{ nullif_placeholder("o.building_number_rules") }} AS building_number_rules,
  {{ nullif_placeholder("o.floor_rules") }} AS floor_rules,
  o.start_time::timestamp AS project_start_time,
  o.end_time::timestamp AS project_end_time,
  o.budget_amount::numeric(18,2) AS budget_amount,
  o.biz_user_id::bigint AS biz_user_id,
  o.manager_id::bigint AS manager_id,
  o.supervisor_id::bigint AS supervisor_id,
  {{ nullif_placeholder("o.customer_type") }} AS customer_type_raw,
  o.tenant_id::bigint AS tenant_id,
  o.last_month_total_rent::numeric(18,2) AS last_month_total_rent,
  o.curing_director::bigint AS curing_director_id,
  {{ nullif_placeholder("o.curing_director_name") }} AS curing_director_name,
  o.settle_start_time::timestamp AS settle_start_time,
  o.settle_end_time::timestamp AS settle_end_time,
  o.check_cycle::integer AS check_cycle,
  {{ nullif_placeholder("o.deliver_time_str") }} AS deliver_time_str,
  {{ nullif_placeholder("o.deliver_reasons") }} AS deliver_reasons,
  o.cow_num::integer AS row_num,
  o.column_num::integer AS column_num,
  o.create_by::bigint AS created_by,
  o.create_time::timestamp AS created_at,
  o.update_by::bigint AS updated_by,
  o.update_time::timestamp AS updated_at,
  {{ nullif_placeholder("o.remark") }} AS remark
FROM {{ source('xycyl_project_ods', 'p_project') }} o
WHERE COALESCE({{ nullif_placeholder("o.del_flag") }}, '0') = '0'
