package com.yuzhi.dts.copilot.ai.service.audit;

import com.yuzhi.dts.copilot.ai.domain.AiAuditLog;
import com.yuzhi.dts.copilot.ai.domain.AiChatMessage;
import com.yuzhi.dts.copilot.ai.domain.AiChatSession;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistry;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.hibernate.cfg.AvailableSettings;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThatCode;

class AiAuditLogJsonbMappingTest {

    private static final String SCHEMA = "copilot_ai_jsonb_test";
    private static final String JDBC_URL = "jdbc:postgresql://localhost:5432/copilot";
    private static final String JDBC_USER = "copilot";
    private static final String JDBC_PASSWORD = "copilot_dev";

    @Test
    void persistsAuditLogWhenMetadataColumnUsesJsonb() throws Exception {
        recreateSchema();

        StandardServiceRegistry registry = new StandardServiceRegistryBuilder()
                .applySetting(AvailableSettings.DRIVER, "org.postgresql.Driver")
                .applySetting(AvailableSettings.URL, JDBC_URL)
                .applySetting(AvailableSettings.USER, JDBC_USER)
                .applySetting(AvailableSettings.PASS, JDBC_PASSWORD)
                .applySetting(AvailableSettings.DIALECT, "org.hibernate.dialect.PostgreSQLDialect")
                .applySetting(AvailableSettings.DEFAULT_SCHEMA, SCHEMA)
                .applySetting(AvailableSettings.HBM2DDL_AUTO, "none")
                .build();

        try (SessionFactory sessionFactory = new MetadataSources(registry)
                .addAnnotatedClass(AiAuditLog.class)
                .buildMetadata()
                .buildSessionFactory()) {
            assertThatCode(() -> persistAuditLog(sessionFactory)).doesNotThrowAnyException();
        } finally {
            StandardServiceRegistryBuilder.destroy(registry);
            dropSchema();
        }
    }

    @Test
    void persistsChatMessageWhenToolCallsColumnUsesJsonb() throws Exception {
        recreateSchema();

        StandardServiceRegistry registry = new StandardServiceRegistryBuilder()
                .applySetting(AvailableSettings.DRIVER, "org.postgresql.Driver")
                .applySetting(AvailableSettings.URL, JDBC_URL)
                .applySetting(AvailableSettings.USER, JDBC_USER)
                .applySetting(AvailableSettings.PASS, JDBC_PASSWORD)
                .applySetting(AvailableSettings.DIALECT, "org.hibernate.dialect.PostgreSQLDialect")
                .applySetting(AvailableSettings.DEFAULT_SCHEMA, SCHEMA)
                .applySetting(AvailableSettings.HBM2DDL_AUTO, "none")
                .build();

        try (SessionFactory sessionFactory = new MetadataSources(registry)
                .addAnnotatedClass(AiChatSession.class)
                .addAnnotatedClass(AiChatMessage.class)
                .buildMetadata()
                .buildSessionFactory()) {
            assertThatCode(() -> persistChatMessage(sessionFactory)).doesNotThrowAnyException();
        } finally {
            StandardServiceRegistryBuilder.destroy(registry);
            dropSchema();
        }
    }

    private void persistAuditLog(SessionFactory sessionFactory) {
        try (Session session = sessionFactory.openSession()) {
            Transaction transaction = session.beginTransaction();
            AiAuditLog entry = new AiAuditLog();
            entry.setUserId("billy.xiezhimin@gmail.com");
            entry.setSessionId("session-1");
            entry.setAction("CHAT_MESSAGE");
            entry.setInput("hello");
            entry.setOutput("world");
            entry.setSuccess(true);
            session.persist(entry);
            session.flush();
            transaction.rollback();
        }
    }

    private void recreateSchema() throws Exception {
        try (Connection connection = DriverManager.getConnection(JDBC_URL, JDBC_USER, JDBC_PASSWORD);
             Statement statement = connection.createStatement()) {
            statement.execute("drop schema if exists " + SCHEMA + " cascade");
            statement.execute("create schema " + SCHEMA);
            statement.execute("""
                    create table %s.ai_audit_log (
                        id bigint generated by default as identity primary key,
                        user_id varchar(128),
                        session_id varchar(64),
                        action varchar(64) not null,
                        tool_name varchar(64),
                        input text,
                        output text,
                        success boolean,
                        error_message text,
                        duration_ms bigint,
                        metadata jsonb,
                        created_at timestamptz
                    )
                    """.formatted(SCHEMA));
            statement.execute("""
                    create table %s.ai_chat_session (
                        id bigint generated by default as identity primary key,
                        session_id varchar(64) not null unique,
                        user_id varchar(128) not null,
                        title varchar(256),
                        data_source_id bigint,
                        status varchar(16),
                        created_at timestamptz,
                        updated_at timestamptz
                    )
                    """.formatted(SCHEMA));
            statement.execute("""
                    create table %s.ai_chat_message (
                        id bigint generated by default as identity primary key,
                        session_id bigint not null references %s.ai_chat_session(id),
                        role varchar(16) not null,
                        content text not null,
                        tool_calls jsonb,
                        tool_call_id varchar(128),
                        tokens_used integer,
                        generated_sql text,
                        routed_domain varchar(32),
                        target_view varchar(128),
                        template_code varchar(64),
                        created_at timestamptz
                    )
                    """.formatted(SCHEMA, SCHEMA));
        }
    }

    private void persistChatMessage(SessionFactory sessionFactory) {
        try (Session session = sessionFactory.openSession()) {
            Transaction transaction = session.beginTransaction();

            AiChatSession chatSession = new AiChatSession();
            chatSession.setSessionId("chat-session-1");
            chatSession.setUserId("billy.xiezhimin@gmail.com");
            chatSession.setStatus("ACTIVE");

            AiChatMessage message = new AiChatMessage();
            message.setRole("assistant");
            message.setContent("hello");
            message.setToolCalls("[]");
            message.setGeneratedSql("select 1");
            message.setRoutedDomain("project");
            message.setTargetView("v_project_overview");
            message.setTemplateCode("project_overview_topn");
            chatSession.addMessage(message);

            session.persist(chatSession);
            session.flush();
            transaction.rollback();
        }
    }

    private void dropSchema() throws Exception {
        try (Connection connection = DriverManager.getConnection(JDBC_URL, JDBC_USER, JDBC_PASSWORD);
             Statement statement = connection.createStatement()) {
            statement.execute("drop schema if exists " + SCHEMA + " cascade");
        }
    }
}
