\set ON_ERROR_STOP on

BEGIN;

CREATE TABLE IF NOT EXISTS public.ods_ptr_mysql_p_contract (
  id bigint,
  customer_id bigint,
  code varchar(255),
  title varchar(255),
  signing_time timestamp,
  status integer,
  start_date timestamp,
  end_date timestamp,
  type varchar(2),
  settlement_method varchar(255),
  discount numeric(10,2),
  business_personnel_id bigint,
  business_personnel_name varchar(60),
  settlement_period varchar(255),
  settlement_period_custom varchar(255),
  invoice_type integer,
  amount_excluding_tax numeric(15,4),
  amount_including_tax numeric(15,4),
  amount_including_tax_and numeric(15,4),
  full_billing_name varchar(255),
  company_name varchar(255),
  address varchar(255),
  duty_paragraph varchar(255),
  bank varchar(255),
  bank_card_no varchar(255),
  contact_number varchar(255),
  create_by bigint,
  create_time timestamp,
  update_by bigint,
  update_time timestamp,
  remark varchar(255),
  del_flag varchar(2),
  invoicing_tax_rate integer,
  parent_id bigint,
  active_child bigint,
  tenant_id bigint,
  settlement_start_date varchar(8),
  verify_type integer,
  verify_day_number integer,
  settlement_type integer,
  month_settlement_money numeric(15,4),
  discount_ratio double precision,
  _dts_source_system varchar(64),
  _dts_source_table varchar(128),
  _dts_import_time timestamp,
  _dts_batch_id varchar(64),
  _dts_execution_id varchar(64),
  _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS public.ods_ptr_mysql_p_floor_layer (
  id bigint,
  project_id bigint,
  floor_number_id bigint,
  floor_code varchar(10),
  floor_name varchar(20),
  floor_name_full varchar(255),
  create_by bigint,
  create_time timestamp,
  update_by bigint,
  update_time timestamp,
  remark varchar(500),
  del_flag varchar(2),
  _dts_source_system varchar(64),
  _dts_source_table varchar(128),
  _dts_import_time timestamp,
  _dts_batch_id varchar(64),
  _dts_execution_id varchar(64),
  _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS public.ods_ptr_mysql_p_floor_number (
  id bigint,
  project_id bigint,
  building_code varchar(10),
  building_name varchar(180),
  building_name_full varchar(500),
  create_by bigint,
  create_time timestamp,
  update_by bigint,
  update_time timestamp,
  remark varchar(255),
  del_flag varchar(2),
  _dts_source_system varchar(64),
  _dts_source_table varchar(128),
  _dts_import_time timestamp,
  _dts_batch_id varchar(64),
  _dts_execution_id varchar(64),
  _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS public.ods_ptr_mysql_p_position (
  id bigint,
  project_id bigint,
  type integer,
  floor_number_id bigint,
  floor_number_name varchar(60),
  floor_layer_id bigint,
  floor_layer_name varchar(60),
  region varchar(255),
  region_full varchar(255),
  curing_period varchar(255),
  follow_type varchar(255),
  matters_needing_attention varchar(255),
  create_by bigint,
  create_time timestamp,
  update_by bigint,
  update_time timestamp,
  remark varchar(255),
  del_flag varchar(2),
  contract_dept_id bigint,
  contract_dept_name varchar(255),
  curing_user_id bigint,
  curing_user_name varchar(255),
  alias_name varchar(60),
  status integer,
  _dts_source_system varchar(64),
  _dts_source_table varchar(128),
  _dts_import_time timestamp,
  _dts_batch_id varchar(64),
  _dts_execution_id varchar(64),
  _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS public.ods_ptr_mysql_p_position_adjustment (
  id bigint,
  code varchar(255),
  title varchar(255),
  project_id bigint,
  project_name varchar(255),
  apply_user_id bigint,
  apply_user_name varchar(255),
  apply_time timestamp,
  status integer,
  create_by bigint,
  create_time timestamp,
  update_by bigint,
  update_time timestamp,
  remark varchar(255),
  tenant_id bigint,
  total_adjustment_number integer,
  print_status integer,
  print_time timestamp,
  print_user_id bigint,
  print_user_name varchar(60),
  curing_user_id bigint,
  curing_user_name varchar(64),
  adjustment_type integer,
  task_item_id bigint,
  _dts_source_system varchar(64),
  _dts_source_table varchar(128),
  _dts_import_time timestamp,
  _dts_batch_id varchar(64),
  _dts_execution_id varchar(64),
  _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS public.ods_ptr_mysql_p_position_adjustment_item (
  id bigint,
  position_adjustment_id bigint,
  old_position_id bigint,
  old_position_name varchar(255),
  old_position_full_name varchar(255),
  new_position_id bigint,
  new_position_name varchar(255),
  new_position_full_name varchar(255),
  good_price_id bigint,
  good_name varchar(255),
  good_norms varchar(255),
  good_specs varchar(255),
  good_type integer,
  good_unit varchar(255),
  adjustment_number integer,
  parent_id bigint,
  rent numeric(15,2),
  green_type integer,
  cost numeric(15,2),
  old_green_id bigint,
  _dts_source_system varchar(64),
  _dts_source_table varchar(128),
  _dts_import_time timestamp,
  _dts_batch_id varchar(64),
  _dts_execution_id varchar(64),
  _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS public.ods_ptr_mysql_p_project_green (
  id bigint,
  project_id bigint,
  project_name varchar(255),
  position_id bigint,
  position_name varchar(255),
  position_full_name varchar(255),
  green_type integer,
  good_name varchar(255),
  good_price_id bigint,
  good_type integer,
  good_norms varchar(255),
  good_specs varchar(255),
  good_unit varchar(255),
  status integer,
  rent_mode integer,
  rent numeric(15,2),
  cost numeric(15,2),
  pose_time timestamp,
  parent_id bigint,
  good_number integer,
  create_by bigint,
  create_time timestamp,
  update_by bigint,
  update_time timestamp,
  remark varchar(255),
  del_flag varchar(2),
  import_status integer,
  total_number integer,
  lock_change_number integer,
  lock_cut_number integer,
  lock_transfer_number integer,
  lock_bad_number integer,
  lock_adjustment_number integer,
  last_cost numeric(15,2),
  _dts_source_system varchar(64),
  _dts_source_table varchar(128),
  _dts_import_time timestamp,
  _dts_batch_id varchar(64),
  _dts_execution_id varchar(64),
  _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS public.ods_ptr_mysql_b_goods (
  id bigint,
  name varchar(255),
  code varchar(255),
  type integer,
  unit varchar(255),
  specifications varchar(255),
  status integer,
  create_by bigint,
  create_time timestamp,
  update_by bigint,
  update_time timestamp,
  del_flag varchar(2),
  remark varchar(255),
  tenant_id bigint,
  category varchar(255),
  goods_classify_id bigint,
  _dts_source_system varchar(64),
  _dts_source_table varchar(128),
  _dts_import_time timestamp,
  _dts_batch_id varchar(64),
  _dts_execution_id varchar(64),
  _dts_task_id varchar(64)
);

CREATE TABLE IF NOT EXISTS public.ods_ptr_mysql_b_goods_price (
  id bigint,
  goods_id bigint,
  goods_code varchar(255),
  create_by bigint,
  create_time timestamp,
  remark varchar(255),
  del_flag varchar(2),
  goods_name varchar(255),
  specifications text,
  goods_att text,
  goods_type integer,
  guidance_price numeric(10,2),
  cost_price numeric(10,2),
  unit varchar(20),
  good_category varchar(255),
  status integer,
  _dts_source_system varchar(64),
  _dts_source_table varchar(128),
  _dts_import_time timestamp,
  _dts_batch_id varchar(64),
  _dts_execution_id varchar(64),
  _dts_task_id varchar(64)
);

COMMIT;
